// <auto-generated />
namespace JobsPortal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class removedateto : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removedateto));
        
        string IMigrationMetadata.Id
        {
            get { return "201711260924457_remove date to "; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
