// <auto-generated />
namespace JobsPortal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addcompanyidtojoboffers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addcompanyidtojoboffers));
        
        string IMigrationMetadata.Id
        {
            get { return "201710091646240_add company id to joboffers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
